# Default values for mo-ruler-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

moRuler:
  replicaCount: 1
  
  image:
    containerName: mo-ruler
    repository: 141549464311.dkr.ecr.us-west-2.amazonaws.com/matrixone-cloud/observability
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "mo-ruler-v0.7.0"

  nameOverride: ""
  fullnameOverride: ""
  
  service:
    type: ClusterIP
    port: 9199
    targetPort: 9199 

  apiServer:
    port: 9199
  
  rulerSpec:
    global:
        evaluation_interval: 60s

    rule_files:
        - "/rules/*.yaml"
        - "/rules/*.yml"

    alerting:
      alertingEndpoint:
        scheme: http
        targets:
      #     - "alertmanager:9093"
    log:
        level: debug
        format: console
        filename:
        maxSize:
        maxDays:
        maxBackups:
    ruler:
      rule:
        ruleType: metric
        notificationQueueCapacity: 10000
        outageTolerance: 1h
        forGracePeriod: 10m
        resendDelay: 1m
        metricConfigPath: /ruler-prometheus.yml
      mo:
        host: matrixone
        port: 6001
        user: dump
        password: 111
        database: observability
        connectTimeout: 5s
        maxOpens: 5
        maxIdles: -1
        initPingCnt: 10
      query:
        maxQueryTimeout: 2m
        subQueryStepInterval: 1m
        lookBackDelta: 5m
        maxSamples: 50000000
        maxPointsPerTs: 11000
      apiServer:
        lookBackDelta: 5m
        listenAddress: 0.0.0.0:9199
        readTimeout: 5m
        maxConnections: 512
        routePrefix: /
        consoleTemplatesPath: consoles
        consoleLibrariesPath: console_libraries
        enableLifecycle: false
        pageTitle: MO-Ruler Server
        appName: MO-Ruler