# mo-agent-stack/templates/rabc.yaml
# example: aliyun/cos-component/local-system-service/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app: mo-ob
rules:
- apiGroups:
    - ""
  resources: 
    - secrets
    - namespaces
  verbs: 
    - get
    - watch
    - list
- apiGroups:
    - core.matrixone-cloud
  resources:
    - clusters
  verbs: 
    - get
    - watch
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app: mo-agent
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
