apiVersion: v2
name: mo-ob-opensource
description: mo-ob-opensource's Helm chart for Kubernetes
type: application
version: 0.9.0-alpha.3
appVersion: 0.9.0
dependencies:
- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 45.9.1
- condition: loki-stack.enabled
  name: loki-stack
  repository: https://grafana.github.io/helm-charts
  version: 2.9.10

