apiVersion: v2
name: mo-ruler-stack
description: MO-Ruler's Helm chart for Kubernetes
dependencies:
- condition: alertmanager.enabled
  name: alertmanager
  repository: https://prometheus-community.github.io/helm-charts
  version: 0.27.*
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.47.*
version: 0.9.1-alpha.1
type: application
appVersion: "0.9.0"
