apiVersion: v1
kind: Secret
metadata:
  name: auth-generic-oauth-secret
data:
  client_id: {{.Values.secretValue.auth_generic_oauth_secret.id}}
  client_secret: {{.Values.secretValue.auth_generic_oauth_secret.secret}}
type: Opaque
