apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
type: Opaque
data:
  admin-user: {{ printf "%s" "admin" | b64enc | quote }}
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}
