apiVersion: v1
kind: Service
metadata:
  name: mo-ruler-service
  labels:
    app-name: mo-ruler
spec:
  type: {{ .Values.moRuler.service.type }}
  selector:
    app: mo-ruler
  ports:
    - name: http
      port: {{ .Values.moRuler.service.port }}
      targetPort: {{ .Values.moRuler.service.targetPort }}
      protocol: TCP
    # - name: https
    #   port: {{ .Values.moRuler.service.port }}
    #   targetPort: {{ .Values.moRuler.service.targetPort }}
    #   protocol: TCP