apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook-adapter
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: alertmanager-webhook-adapter
  sessionAffinity: None