{
 "title": "MO-OB Auth Service Metrics",
 "tags": [ "MO-Cloud" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Auth Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Auth Service API Access Total (without /healthcheck and /metrics) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/login\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/trial/verify\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/assets/*filepath\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/refresh\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/trial/request\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/account/contact\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/org/member/list\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/signup\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/verify\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/trial/invite\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/account/describe\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Service API Error",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "auth_service_api_access_total{path=\"/login\", code!=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/trial/verify\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/assets/*filepath\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/refresh\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/trial/request\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/account/contact\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/org/member/list\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/signup\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/verify\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/trial/invite\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (auth_service_api_access_total{path=\"/account/describe\", code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Avg Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "/account/describe Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/account/describe\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/account/describe\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/account/contact Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/account/contact\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/account/contact\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/assets/*filepath Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/assets/*filepath\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/assets/*filepath\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/healthcheck Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/healthcheck\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/healthcheck\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/login Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/login\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/login\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/metrics Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/metrics\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/metrics\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/org/member/list Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/org/member/list\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/org/member/list\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/refresh Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/refresh\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/refresh\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/signup Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/signup\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/signup\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/trial/request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/trial/request\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/trial/request\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/trial/invite Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/trial/invite\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/trial/invite\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/trial/verify Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/trial/verify\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/trial/verify\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  {
   "title": "/verify Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "auth_service_api_durations_ms_sum{path=\"/verify\"}",
     "legendFormat": "{{path}}-ms-sum"
    },
    {
     "expr": "auth_service_api_durations_ms_count{path=\"/verify\"}",
     "legendFormat": "{{path}}-ms-count"
    }
   ]
  },
  { "title": "API Le Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "/account/describe Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{path=\"/account/describe\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/assets/*filepath Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "{path=\"/assets/*filepath\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/account/contact Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "{path=\"/account/contact\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/healthcheck Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "{path=\"/healthcheck\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/login Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "{path=\"/login\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/metrics Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "{path=\"/metrics\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/org/member/list Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "{path=\"/org/member/list\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/refresh Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "{path=\"/refresh\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/signup Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "{path=\"/signup\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/trial/invite Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "{path=\"/trial/invite\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/trial/request Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "{path=\"/trial/request\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/trial/verify Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "{path=\"/trial/verify\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  },
  {
   "title": "/verify Le Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "{path=\"/verify\"}",
     "legendFormat": "le-{{le}}"
    }
   ]
  }
 ]
}