{
 "title": "MO-OB Cluster Service Metrics",
 "tags": [ "MO-Cloud" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Auth Service API Access Total (without /healthcheck and /metrics) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/healthcheck\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/metrics\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/CreateInstance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeClientIP\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeDBPlatformURL\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeInstanceInfo\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeInstanceStatus\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeInstances\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/RecoverInstance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/TerminateInstance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/UpdateInstance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/instance/metric/runtime\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Service API Error",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/healthcheck\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/metrics\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/CreateInstance\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeClientIP\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeDBPlatformURL\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeInstanceInfo\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeInstanceStatus\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/DescribeInstances\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/RecoverInstance\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/TerminateInstance\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/UpdateInstance\", code!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(path) (cluster_service_api_access_total{path=\"/instance/metric/runtime\", code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Avg Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "/CreateInstance Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/CreateInstance\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/CreateInstance\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/DescribeClientIP Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/DescribeClientIP\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/DescribeClientIP\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/DescribeDBPlatformURL Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/DescribeDBPlatformURL\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/DescribeDBPlatformURL\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/DescribeInstanceInfo Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/DescribeInstanceInfo\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/DescribeInstanceInfo\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/DescribeInstanceStatus Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/DescribeInstanceStatus\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/DescribeInstanceStatus\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/DescribeInstances Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/DescribeInstances\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/DescribeInstances\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/RecoverInstance Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/RecoverInstance\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/RecoverInstance\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/TerminateInstance Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/TerminateInstance\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/TerminateInstance\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/UpdateInstance Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/UpdateInstance\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/UpdateInstance\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/healthcheck Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/healthcheck\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/healthcheck\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/instance/metric/runtime Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/instance/metric/runtime\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/instance/metric/runtime\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    },
    {
     "title": "/metrics  Average Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_sum{path=\"/metrics\"}",
       "legendFormat": "{{path}}-ms-sum"
      },
      {
       "expr": "cluster_service_api_durations_ms_count{path=\"/metrics\"}",
       "legendFormat": "{{path}}-ms-count"
      }
     ]
    }
   ]
  },
  {
   "title": "API Le Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "/CreateInstance Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/CreateInstance\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/DescribeClientIP Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/DescribeClientIP\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/DescribeDBPlatformURL Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/DescribeDBPlatformURL\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/DescribeInstanceInfo Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/DescribeInstanceInfo\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/DescribeInstanceStatus Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/DescribeInstanceStatus\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/DescribeInstances Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/DescribeInstances\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/RecoverInstance Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/RecoverInstance\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/TerminateInstance Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/TerminateInstance\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/UpdateInstance Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/UpdateInstance\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/healthcheck Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/healthcheck\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/instance/metric/runtime Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/instance/metric/runtime\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    },
    {
     "title": "/metrics Le Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "cluster_service_api_durations_ms_bucket{path=\"/metrics\"}",
       "legendFormat": "le-{{le}}"
      }
     ]
    }
   ]
  }
 ]
}