apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-ruler-deployment
  labels:
    app: mo-ruler
spec:
  replicas: {{ .Values.moRuler.replicaCount }}
  selector:
    matchLabels:
      app: mo-ruler
  template:
    metadata:
      labels:
        app: mo-ruler
    spec:
      containers:
      - name: {{ .Values.moRuler.image.containerName }}
        image: "{{ .Values.moRuler.image.repository }}:{{ .Values.moRuler.image.tag }}"
        imagePullPolicy: {{ .Values.moRuler.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.moRuler.apiServer.port }}
        volumeMounts:
          - name: ruler-config
            mountPath: /service.yaml
            subPath: service.yaml

          - name: ruler-prometheus-config
            mountPath: /ruler-prometheus.yml
            subPath: ruler-prometheus.yml

          - name: alert-rules
            mountPath: /rules
      
      volumes:
      - name: ruler-config
        configMap:
          name: mo-ruler-config-map
          items:
          - key: mo-ruler.yaml
            path: service.yaml
      
      - name: ruler-prometheus-config
        configMap:
          name: mo-ruler-config-map
          items:
          - key: ruler-prometheus.yml
            path: ruler-prometheus.yml
        
      - name: alert-rules
        configMap:
          name: rules-config-map
          # items:
          # - key: test_rule.yaml
          #   path: test_rule.yaml