moAgent:
  replicaCount: 1
  image:
    containerName: mo-agent
    pullPolicy: IfNotPresent
    repository: matrixone-cloud/observability
    tag: mo-agent-local
  nameOverride: ""
  fullnameOverride: ""
  agentSpec:
    log:
      level: info
      format: console
      filename:
      maxSize:
      maxDays:
      maxBackups:
    mo:
      host: matrixone.xiezexiong
      #host: mo-tp-cn.xiezexiong
      port: 6001
      user: dump
      password: 111
      connectTimeout: 15s
      maxOpens: 5
      maxIdles: -1
      initPingCnt: 60
    app:
      uuid: 8f0e5ef6de8fe306d772fba5d29e75e8
      account: sys
      database: observability
      # val in [tae, csv], default: tae
      extension: tae
      # val in [sql, fs], default: sql
      exporter: sql
      exportThreads: 128
      exportInterval: 3s
      bufferBytes: 2097152
      showAccessLog: false
      # api data handle queue size
      queueSize : 262144 # queue mem cost : 2MB
      # metric table name cache size
      metricCacheSize : 4096
      # label series id cache size
      labelCacheSize : 200000
      # log table name cache size
      logCacheSize : 512
      preCreatetableWorker : 5
      # pre load label id limit
      labelPreloadLimit : 200000
      labelFlushSize: 5242880 # 5MB
      labelFlushInterval: 6s
      # comment to use values default: prom,node-exporter
      # metricTablesPreCreate: 

prometheus:
  enabled: true
  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 1m
    ## How long until a scrape request times out
    ##
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 1m
  replicaCount: 1
  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true
    extraArgs:
    - --collector.disable-defaults
    - --collector.arp
    - --collector.conntrack
    - --collector.cpu
    - --collector.diskstats
    - --collector.filefd
    - --collector.loadavg
    - --collector.meminfo
    - --collector.netstat
    - --collector.nvme
    - --collector.pressure
    - --collector.schedstat
    - --collector.sockstat
    - --collector.softnet
    - --collector.stat
    - --collector.udp_queues
    - --collector.vmstat
    - --collector.xfs
    - --collector.uname
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$

  server:
    defaultFlagsOverride:
      [
        "--enable-feature=agent",
        "--storage.agent.retention.max-time=30m",
        "--storage.agent.path=/prometheus",
        # "--config.file=/etc/prometheus/config_out/prometheus.env.yaml",
        "--config.file=/etc/config/prometheus.yml",
      ]
    extraFlags:
      - web.enable-lifecycle
    remoteWrite: 
      - url: "http://mo-agent-service.mo-ob:8000/v1/metrics"

  # 这里需要将rule置空，否则报错
  serverFiles:
    prometheus.yml:
      rule_files: []
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
              - localhost:9090        
        - job_name: 'user-application'
          honor_labels: true
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: "mo-cloud"
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+?)(?::\d+)?;(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: service
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: node
        - job_name: 'kubernetes-service-endpoints'
          honor_labels: true
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
              action: drop
              regex: true
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: (.+?)(?::\d+)?;(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: service
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: node
              
fluent-bit:
  enabled: false
  replicaCount: 1
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    # Overrides the image tag whose default is {{ .Chart.AppVersion }}
    tag: 2.0.8-debug
    pullPolicy: Always
  logLevel: info
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
  config:
    inputs: |
      # Whitelist Mode
      [INPUT]
          Name tail
          Path             /var/log/containers/*_cos_*.log,/var/log/containers/*_cos-system_*.log, /var/log/containers/*_mo-cloud_*.log, /var/log/containers/*_mo-system_*.log
          multiline.parser docker, cri, go 
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines Off
          Refresh_Interval  10
      [INPUT]
          Name tail
          Path             /var/log/containers/*mo-log*.log,/var/log/containers/*mo-dn*.log,/var/log/containers/*mo-cn*.log
          multiline.parser docker, cri, go 
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines Off
          Refresh_Interval  10
      [INPUT]
          Name tail
          Path             /var/log/containers/*mo-agent-deployment*.log
          multiline.parser docker, cri, go 
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines Off
          Refresh_Interval  10
      # host-log
      [INPUT]
          Name                tail
          Tag                 host.dmesg
          Path                /var/log/dmesg
          Parser              syslog
          Mem_Buf_Limit       5MB
          Skip_Long_Lines     On
          Refresh_Interval    10
      [INPUT]
          Name                tail
          Tag                 host.messages
          Path                /var/log/messages
          Parser              syslog
          Mem_Buf_Limit       5MB
          Skip_Long_Lines     On
          Refresh_Interval    10
      [INPUT]
          Name                tail
          Tag                 host.secure
          Path                /var/log/secure
          Parser              syslog
          # DB                  /var/fluent-bit/state/flb_secure.db
          Mem_Buf_Limit       5MB
          Skip_Long_Lines     On
          Refresh_Interval    10
    outputs: |
      [OUTPUT]
          Name  http
          Match *
          Host  mo-agent-service.mo-ob
          Port  8000
          URI   /v1/logs
          Format json
      [OUTPUT]
          Name stdout
          Match *
          # Format json
          Json_date_key timestamp
          Json_date_format iso8601

